# basic options
title: Luis Contreras Homepage
author: Luis Contreras
#email: your-email@domain.com

description: > # this means to ignore newlines until "next_option:"
  Luis Contreras' homepage with his latest research, lectures,
  teaching resources, and media appearances.

#twitter_username: TenshiTeacher
github_username:  ARTenshi

header_pages:
 - about.md
 - research.md
 - teaching.md
 - media.md

# Build settings
markdown: kramdown
theme: minima
